DROP TABLE REPORTLIST CASCADE CONSTRAINTS;

CREATE TABLE REPORTLIST
(
    BCODE NUMBER NOT NULL,
    ID VARCHAR2(11) NOT NULL,
    CONSTRAINT REP_BCODE FOREIGN KEY (BCODE) REFERENCES BOARD (BCODE),
    CONSTRAINT REP_ID FOREIGN KEY (ID) REFERENCES MEMBER (ID),
    CONSTRAINT REP_PK PRIMARY KEY (BCODE,ID)
);