DROP TABLE REPORTLIST CASCADE CONSTRAINTS;

CREATE TABLE REPORTLIST
(
    BCODE NUMBER NOT NULL,
    ID VARCHAR2(20) NOT NULL,
    CONSTRAINT REP_BCODE FOREIGN KEY (BCODE) REFERENCES BOARD (BCODE),
    CONSTRAINT REP_ID FOREIGN KEY (ID) REFERENCES MEMBER (ID),
    CONSTRAINT REP_PK PRIMARY KEY (BCODE,ID)
);

DROP TABLE CREPORTLIST CASCADE CONSTRAINTS;

CREATE TABLE CREPORTLIST
(
    CCODE NUMBER NOT NULL,
    ID VARCHAR2(20) NOT NULL,
    CONSTRAINT CREP_CCODE FOREIGN KEY (CCODE) REFERENCES COMMENTS (CCODE),
    CONSTRAINT CREP_ID FOREIGN KEY (ID) REFERENCES MEMBER (ID),
    CONSTRAINT CREP_PK PRIMARY KEY (CCODE,ID)
);