DROP TABLE ITEMMOOD CASCADE CONSTRAINTS;

CREATE TABLE ITEMMOOD
(
    MOOD NUMBER NOT NULL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL
);

INSERT INTO ITEMMOOD VALUES(1,'CRAZY');
INSERT INTO ITEMMOOD VALUES(2,'HAPPY');
INSERT INTO ITEMMOOD VALUES(3,'SAD');
INSERT INTO ITEMMOOD VALUES(4,'BAD');

COMMIT;
