--유저
INSERT INTO MEMBER VALUES(MEM_SEQ.NEXTVAL,'admin','admin','eamil',null,0,0,0,0,0,0,0,null,sysdate,null);
INSERT INTO MEMBER VALUES(MEM_SEQ.NEXTVAL,'user','user','email',null,0,0,0,0,0,0,0,null,sysdate,null);


--게시판 코드
INSERT INTO BOARDCODE VALUES (1,'기업');
INSERT INTO BOARDCODE VALUES (2,'QnA');
INSERT INTO BOARDCODE VALUES (3,'신기술');
INSERT INTO BOARDCODE VALUES (4,'아무말대잔치');
INSERT INTO BOARDCODE VALUES (5,'프로젝트/소스');

--게시판
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'그린캣소프트(주)에서 함께 서비스를 개발하실 신입/초급 개발자를 모십니다','그린캣소프트(주)에서 함께 서비스를 개발하실 신입/초급 개발자를 모십니다',1,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'[프리랜서] 단기/ 웹사이트 구축 JAVA 고급 개발자 구인합니다.','구인해요 ㅎㅎ',1,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'[e커머스 선두업체 정규직] 서비스 개발자를 찾고있습니다.','찾아요 ㅋㅋ',1,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',1,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',1,'admin',SYSDATE,NULL,NULL);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'탕수육 부먹 VS. 찍먹, 당신의 선택은','부먹 1표',2,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'아이언맨이랑 사자랑 싸우면 누가 이기나요?','누가 이김?',2,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'자바가 좋냐 씨가 좋냐','파이썬이 최고',2,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',2,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',2,'admin',SYSDATE,NULL,NULL);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'자바의 몰락 - Part 1','냉무',3,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'인공지능에 대하여...','ABCDEFG',3,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'클라우드 기술에 대해 토론해봅시다.','플리즈',3,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',3,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',3,'admin',SYSDATE,NULL,NULL);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'햄버거 사주세요','제발',4,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'아 게임하고 싶다','게임',4,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'배고파요','밥 사줘',4,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',4,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',4,'admin',SYSDATE,NULL,NULL);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'제 코드 좀 봐주세요','봤으면 사라져',5,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'소스를 훔쳐가는 사람이 있습니다.','그게 바로 나',5,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'이 소스 왜 안되는걸까요','알려줘',5,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'4','4',5,'admin',SYSDATE,NULL,NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'5','5',5,'admin',SYSDATE,NULL,NULL);

--댓글 대댓글
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!','admin',SYSDATE,1,NULL,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!','admin',SYSDATE,1,NULL,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!','admin',SYSDATE,1,NULL,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!','admin',SYSDATE,1,NULL,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!','admin',SYSDATE,1,NULL,5);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@','admin',SYSDATE,1,NULL,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@','admin',SYSDATE,1,NULL,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@','admin',SYSDATE,1,NULL,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@','admin',SYSDATE,1,NULL,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@','admin',SYSDATE,1,NULL,5);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'#','admin',SYSDATE,1,NULL,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'#','admin',SYSDATE,1,NULL,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'#','admin',SYSDATE,1,NULL,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'#','admin',SYSDATE,1,NULL,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'#','admin',SYSDATE,1,NULL,5);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$','admin',SYSDATE,1,NULL,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$','admin',SYSDATE,1,NULL,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$','admin',SYSDATE,1,NULL,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$','admin',SYSDATE,1,NULL,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$','admin',SYSDATE,1,NULL,5);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%','admin',SYSDATE,1,NULL,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%','admin',SYSDATE,1,NULL,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%','admin',SYSDATE,1,NULL,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%','admin',SYSDATE,1,NULL,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%','admin',SYSDATE,1,NULL,5);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,2,1,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,2,1,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,2,1,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,3,26,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,3,26,1);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,2,2,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,2,2,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,2,2,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,3,31,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,3,31,2);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,2,3,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,2,3,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,2,3,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,3,36,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,3,36,3);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,2,4,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,2,4,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,2,4,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,3,41,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,3,41,4);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,2,5,5);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,2,5,5);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,2,5,5);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,3,46,5);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,3,46,5);


--아이템무드
INSERT INTO ITEMMOOD VALUES(1,'CRAZY');
INSERT INTO ITEMMOOD VALUES(2,'HAPPY');
INSERT INTO ITEMMOOD VALUES(3,'SAD');
INSERT INTO ITEMMOOD VALUES(4,'BAD');

--신기술 주제
INSERT INTO WEEKSUBJECT VALUES
(
	NEWTECH_SEQ.NEXTVAL,'첫번째 주제 : 반장의 연애는 30대 전까지 가능하다?',SYSDATE-10
);

INSERT INTO WEEKSUBJECT VALUES
(
	NEWTECH_SEQ.NEXTVAL,'두번째 주제 : 반장의 연애는 40대 전까지 가능하다?',SYSDATE-3
);

COMMIT;