DROP TABLE LEVELING;
CREATE TABLE LEVELING
(
    LEV NUMBER PRIMARY KEY,
    EXP NUMBER NOT NULL
);

DROP SEQUENCE LEV_SEQ;

CREATE SEQUENCE LEV_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

INSERT INTO LEVELING VALUES(LEV_SEQ.NEXTVAL,1);

DECLARE
    LP NUMBER:=1;
    MULTI NUMBER:=2;
BEGIN
    LOOP       
        IF LP>=75 THEN MULTI:=1.1;
        ELSIF LP>=50 THEN MULTI:=1.2;
        ELSIF LP>=25 THEN MULTI:=1.5;
        END IF;
        
        INSERT INTO LEVELING VALUES(LEV_SEQ.NEXTVAL,FLOOR((SELECT MAX(EXP) FROM LEVELING)*MULTI));
        LP:=LP+1;
        
        EXIT WHEN LP>=100;
    END LOOP;       
END;
/
