DROP SEQUENCE MEM_SEQ;
DROP SEQUENCE ITEM_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE ATTACHFILE_SEQ;
DROP SEQUENCE COMMENTS_SEQ;

CREATE SEQUENCE MEM_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE ITEM_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE ATTACHFILE_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE COMMENTS_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE;
