INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,2,1,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,2,1,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,2,1,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,3,26,1);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'!!','admin',SYSDATE,3,26,1);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,2,2,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,2,2,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,2,2,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,3,31,2);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'@@','admin',SYSDATE,3,31,2);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,2,3,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,2,3,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,2,3,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,3,36,3);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'##','admin',SYSDATE,3,36,3);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,2,4,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,2,4,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,2,4,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,3,41,4);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'$$','admin',SYSDATE,3,41,4);

INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,2,5,5);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,2,5,5);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,2,5,5);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,3,46,5);
INSERT INTO COMMENTS VALUES(COMMENTS_SEQ.NEXTVAL,'%%','admin',SYSDATE,3,46,5);
COMMIT;