INSERT INTO BOARDCODE VALUES (1,'기업');
INSERT INTO BOARDCODE VALUES (2,'QnA');
INSERT INTO BOARDCODE VALUES (3,'신기술');
INSERT INTO BOARDCODE VALUES (4,'아무말대잔치');
INSERT INTO BOARDCODE VALUES (5,'프로젝트/소스');

COMMIT;