CREATE OR REPLACE TRIGGER BOARD_TRI
AFTER INSERT ON BOARD
FOR EACH ROW

BEGIN	
    INSERT INTO BOARDPOINT
    VALUES(:NEW.BCODE,0,0,0,0,0,0);
END; 
/

CREATE OR REPLACE TRIGGER COMMENT_TRI
AFTER INSERT ON COMMENTS
FOR EACH ROW

BEGIN	
    INSERT INTO COMMENTSPOINT
    VALUES(:NEW.CCODE,0,0,0);
END; 
/

